### PR TITLE
Added SushiScans

### PR DESCRIPTION
**Pull request by btylerh7**

### CODE REVIEW

**Comment by TheNetsky** [comment]
Tested?
Also does it not support notifications?

**Comment by btylerh7** [comment]
It has been tested. I did notice one issue this morning after making the pr. Manga Status is listed in French, so I'll have to make a quick change. Will do that later today.

**Comment by btylerh7** [comment]
After running some more tests, here's an update:
- All tests successful
- Added notifications tag, notifications **are** supported
- I had to add an extra possible selector to a part of the `parseUpdatedManga` function. If that is a problem, let me know and I will try to figure something else out.
-  I updated the name everywhere to SushiScan (no s) because I realized I had that wrong and it bothered me.

I do have one question about the `dateTimeAgo` object:
- Is there an easy way to confirm what the website is using to show a manga was uploaded "just now" other than trying to catch when the site uploads a manga?
  - I can test most of the others pretty easily, but I do not know exactly what they are using and the site is in French, so it is probably different.

**Comment by TheNetsky** [comment]
> I do have one question about the `dateTimeAgo` object:
> 
> * Is there an easy way to confirm what the website is using to show a manga was uploaded "just now" other than trying to catch when the site uploads a manga?
>   
>   * I can test most of the others pretty easily, but I do not know exactly what they are using and the site is in French, so it is probably different.

No there's not. Not that it really matters, if they refresh x minutes later it'll work since the time has changed till x minutes ago.

**Pull request merged**
