### PR TITLE
Added Kraw

### PR DESCRIPTION
**Pull request by btylerh7**
Saw this source on the source requests before someone changed the url to a different site, but I figured I'd make it anyway.

I'm pretty sure this is using the new MangaReader template, so I made some changes to the parseMangaDetails function and I believe works now. I notated all the specific changes with comments.

### CODE REVIEW

**Comment by niclimcy** [comment]
Genres tab is also a bit different with mangareader cms, you might need to change that too

**Comment by btylerh7** [comment]
Oh you're right I see that now. I'll try to fix that sometime today.

**Comment by btylerh7** [comment]
After double checking, tags seem to work correctly without needing to make changes.

**Comment by TheNetsky** [comment]
For starters don't change the package.json or package-lock.json.

Also I'm looking into this later, since more sources will need this. So it might be better to incorporate this into the main parser instead of per source.

**Comment by btylerh7** [comment]
Changing the package.json was accidental. I put it back like it was to start with. 

And yes, it would probably be better to put it in the parser. Would you rather me just leave this until that's done?

**Comment by TheNetsky** [comment]
> Changing the package.json was accidental. I put it back like it was to start with.
> 
> And yes, it would probably be better to put it in the parser. Would you rather me just leave this until that's done?

If you can make a pretty yet functional solution that'll make it compatible, feel free. Even if it just means making more overridable selectors.

**Pull request closed without merging**
